name: Three Step Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Step 1 - Initialization
        run: echo "Starting the workflow..."

      - name: ✅ Step 2 - Adding Two Numbers
        run: |
          num1=10
          num2=20
          sum=$((num1 + num2))
          echo "The sum of $num1 and $num2 is: $sum"

      - name: ✅ Step 3 - Final
        run: echo "Workflow Completed Successfully ✅"
