name: Three Step Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Initialization
        run: echo "Initialization Completed"

      - name: ✅ Execution
        run: echo "Execution Completed"

      - name: ✅ Final
        run: echo "Final Stage Completed"
